Repository resource-watch/resource-watch, pull requests merged in 2021-09, with the labels that each got.

#1772 Ocean Watch: country page anchors
  CHANGELOG.md
  css/layouts/_ocean-watch.scss
  package.json
  pages/dashboards/ocean-watch/country/[iso].jsx
  public/static/data/ocean-watch.json
  yarn.lock
Labels: Ocean Watch

#1774 collapsible mini-explore
  CHANGELOG.md
  components/mini-explore/datasets-sidebar/component.jsx
  components/mini-explore/datasets-sidebar/index.jsx
  components/mini-explore/styles.scss
  package.json
  yarn.lock
Labels: Ocean Watch

#1777 added back to top button to storytelling
  CHANGELOG.md
  css/layouts/_ocean-watch.scss
  layout/layout/ocean-watch/storytelling/component.jsx
Labels: Ocean Watch

#1778 storytelling: worldwide geostore
  CHANGELOG.md
  layout/layout/ocean-watch/storytelling/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/index.jsx
  pages/dashboards/ocean-watch/index.jsx
Labels: Ocean Watch

#1781 preproduction <-- develop
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/unexpected.md
  .github/pull_request_template.md
  CHANGELOG.md
  README.md
  components/app/common/Banner.jsx
  components/card-indicator-set/numeric-card-indicator/component.jsx
  components/mini-explore/datasets-sidebar/component.jsx
  components/mini-explore/datasets-sidebar/index.jsx
  components/mini-explore/styles.scss
  components/ui/accordion/styles.scss
  css/components/app/common/banner.scss
  css/components/form/select.scss
  css/layouts/_footer.scss
  css/layouts/_ocean-watch.scss
  docker-compose-develop.yml
  layout/layout/ocean-watch/storytelling/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/index.jsx
  next.config.js
  package.json
  pages/dashboards/ocean-watch/country/[iso].jsx
  pages/dashboards/ocean-watch/country/index.jsx
  pages/dashboards/ocean-watch/index.jsx
  public/static/data/ocean-watch.json
  public/static/images/ocean-watch/placeholder-map.png
  yarn.lock
Labels: release

#1771 Add env columns to back office tables
  components/admin/data/layers/table/component.js
  components/admin/data/widgets/table/component.js
  components/admin/pages/table/PagesTable.js
  components/admin/partners/table/component.js
  components/admin/tools/table/ToolsTable.js
  components/dashboards/table/DashboardsTable.js
  components/datasets/table/component.js
Labels: data env configuration

#1776 ocean watch: duplicates data structure to production
  public/static/data/ocean-watch.json
Labels: Ocean Watch, data

#1783 preproduction <-- develop
  components/admin/data/layers/table/component.js
  components/admin/data/widgets/table/component.js
  components/admin/pages/table/PagesTable.js
  components/admin/partners/table/component.js
  components/admin/tools/table/ToolsTable.js
  components/dashboards/table/DashboardsTable.js
  components/datasets/table/component.js
  public/static/data/ocean-watch.json
Labels: release

#1790 fixes wrong default value for partners
  layout/app/partners/component.jsx
Labels: release

#1793 fixes explore route on update
  CHANGELOG.md
  pages/data/explore/[[...dataset]].jsx
Labels: bug

#1794 preproduction <-- develop
  CHANGELOG.md
  components/card-indicator-set/indicator-visualization/component.jsx
  components/card-indicator-set/indicator-visualization/styles.scss
  components/embed/powered-by/component.jsx
  components/embed/powered-by/index.js
  components/mini-explore-widgets/component.jsx
  components/widgets/share-modal/component.jsx
  components/widgets/types/chart/component.jsx
  components/widgets/types/chart/index.jsx
  components/widgets/types/map/component.jsx
  components/widgets/types/map/index.jsx
  css/components/widget.scss
  layout/embed/map/component.jsx
  layout/embed/map/index.js
  layout/embed/map/index.jsx
  layout/embed/map/selectors.js
  layout/embed/widget/component.jsx
  layout/embed/widget/index.js
  layout/embed/widget/index.jsx
  package.json
  pages/dashboards/ocean-watch/country/[iso].jsx
  pages/dashboards/ocean-watch/partners/index.jsx
  pages/data/explore/[[...dataset]].jsx
  pages/embed/map/[id].jsx
  pages/embed/widget/[id].jsx
  public/static/data/ocean-watch.json
  services/webshot.js
  utils/embed.js
  yarn.lock
Labels: release

#1795 preproduction <-- develop
  pages/dashboards/ocean-watch/country/[iso].jsx
  utils/widget.js
Labels: release

#1797 adds text blocks
  CHANGELOG.md
  public/static/data/ocean-watch.json
Labels: Ocean Watch

#1798 increases zoom one level
  CHANGELOG.md
  layout/layout/ocean-watch/map/component.jsx
Labels: Ocean Watch

#1800 updates text and link for suggest a story banner
  CHANGELOG.md
  pages/dashboards/ocean-watch/country/[iso].jsx
  pages/dashboards/ocean-watch/index.jsx
Labels: Ocean Watch

#1802 preproduction <-- develop
  CHANGELOG.md
  components/widgets/types/map-swipe/component.jsx
  layout/embed/map/component.jsx
  layout/layout/ocean-watch/map/component.jsx
  pages/dashboards/ocean-watch/country/[iso].jsx
  pages/dashboards/ocean-watch/index.jsx
  pages/embed/map/[id].jsx
  pages/webshot/[id].jsx
  public/static/data/ocean-watch.json
Labels: release

#1775 Add missing env selects
  components/admin/data/layers/form/steps/Step1.js
  components/admin/data/widgets/form/steps/component.jsx
  components/admin/pages/form/steps/Step1.js
  components/admin/partners/form/steps/Step1.js
  components/admin/tools/form/steps/Step1.js
  components/dashboards/form/steps/step-1/component.jsx
  components/datasets/form/steps/component.js
Labels: data env configuration

#1761 Add `env` parameter to all app requests
  services/areas.js
  services/collections.js
  services/dashboard.js
  services/dataset.js
  services/faqs.js
  services/favourites.js
  utils/axios.js
Labels: data env configuration

#1782 Add new env variables: NEXT_PUBLIC_ENVS_SHOW, NEXT_PUBLIC_ENVS_EDIT
  .env.development
  .env.production
  components/admin/data/layers/table/component.js
  components/admin/data/widgets/form/component.js
  components/admin/data/widgets/form/steps/component.jsx
  components/admin/data/widgets/table/component.js
  components/admin/pages/form/steps/Step1.js
  components/admin/pages/table/PagesTable.js
  components/admin/partners/form/PartnersForm.js
  components/admin/partners/table/component.js
  components/admin/tags/TagsForm.js
  components/admin/tools/form/ToolsForm.js
  components/admin/tools/table/ToolsTable.js
  components/app/static-pages/get-involved/post-content/Apps.js
  components/dashboards/form/steps/step-1/component.jsx
  components/dashboards/table/DashboardsTable.js
  components/datasets/form/DatasetsForm.js
  components/datasets/form/steps/component.js
  components/datasets/metadata/form/component.js
  components/datasets/similar-datasets/similar-datasets-actions.js
  components/datasets/table/component.js
  components/form/Navigation.js
  components/mini-explore/datasets-sidebar/index.jsx
  components/mini-explore/map/index.jsx
  components/ui/SearchInput.js
  components/ui/customtable/content/TableContent.js
  components/widgets/metadata/form/MetadataForm.js
  css/_base.scss
  layout/app/dashboards/component.jsx
  layout/app/home/component.jsx
  layout/app/partners/component.jsx
  layout/explore/actions.js
  layout/explore/explore-collections/component.jsx
  layout/explore/explore-detail/related-content/index.js
  layout/explore/explore-discover/component.js
  layout/explore/explore-favorites/component.jsx
  layout/explore/explore-my-data/component.jsx
  layout/explore/explore-near-real-time/index.js
  layout/footer/footer-links/component.jsx
  layout/footer/partners-carousel/index.jsx
  layout/header/header-dashboards/component.jsx
  modules/partners/actions.js
  redactions/admin/pages.js
  redactions/admin/tools.js
  services/dataset.js
  services/pages.js
  services/partners.js
  services/widget.js
Labels: data env configuration

#1808 Feature/staging back office fixes
  components/admin/data/layers/table/component.js
  components/admin/data/widgets/form/steps/component.jsx
  components/admin/data/widgets/table/component.js
  components/admin/pages/form/PagesForm.js
  components/admin/partners/form/PartnersForm.js
  components/admin/tools/form/ToolsForm.js
  components/datasets/table/component.js
Labels: work-in-progress

#1807 data environments docs
  README.md
Labels: documentation

#1813 adds custom anchor titles
  CHANGELOG.md
  pages/dashboards/ocean-watch/country/[iso].jsx
  public/static/data/ocean-watch.json
Labels: Ocean Watch

#1814 mini-explore-widgets: fixes data placeholder
  CHANGELOG.md
  components/mini-explore-widgets/component.jsx
  components/mini-explore-widgets/reducer.js
Labels: bug, Ocean Watch

#1822 preproduction <-- develop
  components/card-indicator-set/numeric-card-indicator/index.jsx
  hooks/partners/index.js
  layout/app/partners/component.jsx
  layout/footer/partners-carousel/index.jsx
  layout/layout/ocean-watch/partners/index.jsx
  layout/layout/ocean-watch/storytelling/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/index.jsx
  pages/dashboards/ocean-watch/partners/index.jsx
  public/static/data/ocean-watch.json
Labels: release

#1826 preproduction <-- develop
  components/card-indicator-set/indicator-visualization/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/component.jsx
  layout/layout/ocean-watch/storytelling/story-step/index.jsx
  public/static/data/ocean-watch.json
Labels: release

#1830 preproduction <-- develop
  components/mini-explore-widgets/component.jsx
  pages/dashboards/ocean-watch/country/[iso].jsx
  public/static/data/ocean-watch.json
Labels: release

#1833 preproduction <-- develop
  components/card-indicator-set/indicator-visualization/styles.scss
  layout/embed/map-swipe/component.jsx
  layout/embed/map/component.jsx
  layout/embed/widget/component.jsx
  pages/webshot/[id].jsx
  public/static/data/ocean-watch.json
Labels: release

#1834 Deploy/production
  components/card-indicator-set/indicator-visualization/styles.scss
  public/static/data/ocean-watch.json
Labels: release

#1837 preproduction <-- develop
  components/card-indicator-set/indicator-visualization/component.jsx
  components/card-indicator-set/numeric-card-indicator/component.jsx
  components/card-indicator-set/numeric-card-indicator/styles.scss
  public/static/data/ocean-watch.json
Labels: release

#1839 preproduction <-- develop
  layout/embed/map-swipe/component.jsx
  layout/embed/widget/component.jsx
  public/static/data/ocean-watch.json
Labels: release

#1840 Deploy/production
  components/card-indicator-set/indicator-visualization/component.jsx
  components/card-indicator-set/numeric-card-indicator/component.jsx
  components/card-indicator-set/numeric-card-indicator/styles.scss
  layout/embed/map-swipe/component.jsx
  layout/embed/widget/component.jsx
  public/static/data/ocean-watch.json
Labels: release
