Repository resource-watch/resource-watch, pull requests merged in 2021-03, with the labels that each got.

#1594 fixes issue populating open graph tags in dashboards pages
  .gitignore
  CHANGELOG.md
  layout/app/dashboard-detail/component.jsx
  pages/app/dashboards-detail/index.jsx
Labels: bug

#1595 production deployment
  .gitignore
  CHANGELOG.md
  layout/app/dashboard-detail/component.jsx
  pages/app/dashboards-detail/index.jsx
Labels: release

#1596 fixed issue with user areas overlapping with dataset detail view in E…
  CHANGELOG.md
  layout/explore/component.jsx
Labels: bug

#1597 dashboards testing
  .eslintrc.json
  .gitignore
  components/dashboards/form/DashboardsForm.js
  cypress.json
  cypress/fixtures/areas/get-user-areas.json
  cypress/fixtures/cat-2.jpg
  cypress/fixtures/cat.jpg
  cypress/fixtures/dashboard.json
  cypress/fixtures/dashboards/get-all/output.json
  cypress/fixtures/dashboards/patch/input.json
  cypress/fixtures/dashboards/patch/output.json
  cypress/fixtures/dashboards/post/input.json
  cypress/fixtures/dashboards/post/output.json
  cypress/fixtures/subscriptions/get-all.json
  cypress/integration/dashboards.spec.js
  cypress/support/commands.js
  cypress/support/index.js
  docker-compose-test.yml
  package.json
  pages/_app.js
  redactions/user.js
  test/payload/user.js
  yarn.lock
Labels: tests, work-in-progress

#1601 runs name-default-component codemod
  CHANGELOG.md
  pages/sign-in/index.jsx
  redactions/admin/dashboards.js
  redactions/admin/datasets.js
  redactions/admin/faqs.js
  redactions/admin/pages.js
  redactions/admin/partners.js
  redactions/admin/sources.js
  redactions/admin/tools.js
  redactions/dashboards.js
  redactions/insights.js
  redactions/modal.js
  redactions/page.js
  redactions/routes.js
  redactions/tooltip.js
  redactions/user.js
  redactions/widget.js
Labels: maintenance

#1604 Update cypress to 6.6.0
  Dockerfile.cypress
  package.json
Labels: dependencies

#1603 bitly@7.1.2
  CHANGELOG.md
  components/modal/share-modal/share-modal-actions.js
  cypress/integration/components/share-modal.spec.js
  layout/app/dashboard-detail/component.jsx
  package.json
  yarn.lock
Labels: dependencies

#1611 fixes static pages
  CHANGELOG.md
  components/admin/pages/form/PagesForm.js
  components/admin/pages/table/PagesTable.js
  components/admin/pages/table/td/name/component.js
  components/admin/pages/table/td/name/component.jsx
  components/admin/pages/table/td/name/index.js
  hooks/static-pages/fetch-static-page.js
  layout/admin/pages-detail/component.js
  layout/admin/pages-detail/component.jsx
  layout/admin/pages-detail/index.js
  layout/admin/pages/component.js
  layout/admin/pages/component.jsx
  layout/admin/pages/constants.js
  layout/admin/pages/index.js
  modules/static-pages/actions.js
  pages/admin/pages-detail/index.js
  pages/admin/pages-detail/index.jsx
  pages/admin/pages/index.js
  pages/admin/pages/index.jsx
  redactions/admin/pages.js
  services/static-page.js
Labels: bug, ready to review

#1614 Deploy/master
  CHANGELOG.md
  components/admin/data/layers/form/layer-preview/component.js
  components/admin/pages/form/PagesForm.js
  components/admin/pages/table/PagesTable.js
  components/admin/pages/table/td/name/component.js
  components/admin/pages/table/td/name/component.jsx
  components/admin/pages/table/td/name/index.js
  components/datasets/list/list-item/component.jsx
  components/map/controls/styles.scss
  components/map/styles.scss
  components/ui/map/Map.js
  components/wysiwyg/widget-block/component.js
  css/components/map/map.scss
  hooks/static-pages/fetch-static-page.js
  layout/admin/pages-detail/component.js
  layout/admin/pages-detail/component.jsx
  layout/admin/pages-detail/index.js
  layout/admin/pages/component.js
  layout/admin/pages/component.jsx
  layout/admin/pages/constants.js
  layout/admin/pages/index.js
  modules/static-pages/actions.js
  next.config.js
  package.json
  pages/admin/pages-detail/index.js
  pages/admin/pages-detail/index.jsx
  pages/admin/pages/index.js
  pages/admin/pages/index.jsx
  redactions/admin/pages.js
  services/static-page.js
  yarn.lock
Labels: release

#1615 reverts deploy master
  CHANGELOG.md
  components/admin/data/layers/form/layer-preview/component.js
  components/admin/pages/form/PagesForm.js
  components/admin/pages/table/PagesTable.js
  components/admin/pages/table/td/name/component.js
  components/admin/pages/table/td/name/component.jsx
  components/admin/pages/table/td/name/index.js
  components/datasets/list/list-item/component.jsx
  components/map/controls/styles.scss
  components/map/styles.scss
  components/ui/map/Map.js
  components/wysiwyg/widget-block/component.js
  css/components/map/map.scss
  hooks/static-pages/fetch-static-page.js
  layout/admin/pages-detail/component.js
  layout/admin/pages-detail/component.jsx
  layout/admin/pages-detail/index.js
  layout/admin/pages/component.js
  layout/admin/pages/component.jsx
  layout/admin/pages/constants.js
  layout/admin/pages/index.js
  modules/static-pages/actions.js
  next.config.js
  package.json
  pages/admin/pages-detail/index.js
  pages/admin/pages-detail/index.jsx
  pages/admin/pages/index.js
  pages/admin/pages/index.jsx
  redactions/admin/pages.js
  services/static-page.js
  yarn.lock
Labels: release

#1616 release preproduction
  CHANGELOG.md
  layout/explore/explore-map/component.jsx
Labels: release

#1619 release preproduction
  .github/pull_request_template.md
  CHANGELOG.md
  components/modal/login-modal/component.jsx
  cypress.json
  cypress/integration/user/registration.spec.js
  cypress/plugins/index.js
  layout/app/dashboard-detail/energy-country-explorer/component.js
  package.json
  public/static/data/CountryEnergyExplorer.json
  services/user.js
  yarn.lock
Labels: release
